name: Export to Coralogix

on:
  workflow_run:
    workflows: ['*']
    types: [completed]

permissions: read-all

jobs:
  Coralogix-Exporter:
    uses: Appcharge/github-actions-warehouse/.github/workflows/cx-exporter.yaml@master
    with:
      source_branch: ${{ github.ref_name }}
    secrets:
      CORALOGIX_API_KEY: ${{ secrets.CORALOGIX_API_KEY }}
      CORALOGIX_API_KEY_NP: ${{ secrets.CORALOGIX_API_KEY_NP }}
